"""Build held-out set 5: sites chosen from general knowledge before any page is read,
none on an earlier set or spot check (hosts are checked automatically).

  python scripts/make_heldout5.py USED_HOSTS.json > scripts/toolbench-heldout5.json
"""
import json
import sys

# (site, category, url, expect): expect is a word the real page must mention 3+ times.
CANDIDATES = [
    # US retail
    ("wayfair", "retail_us", "https://www.wayfair.com/keyword.php?keyword=desk+lamp", "lamp"),
    ("kohls", "retail_us", "https://www.kohls.com/search.jsp?search=towel", "towel"),
    ("jcpenney", "retail_us", "https://www.jcpenney.com/s/pillow", "pillow"),
    ("macys", "retail_us", "https://www.macys.com/shop/search?keyword=wallet", "wallet"),
    ("nordstrom", "retail_us", "https://www.nordstrom.com/sr?keyword=sneakers", "sneaker"),
    ("rei", "retail_us", "https://www.rei.com/search?q=backpack", "backpack"),
    ("dickssportinggoods", "retail_us", "https://www.dickssportinggoods.com/search/SearchDisplay?searchTerm=basketball", "basketball"),
    ("academy", "retail_us", "https://www.academy.com/search?searchTerm=cooler", "cooler"),
    ("petco", "retail_us", "https://www.petco.com/shop/en/petcostore/search?query=cat%20litter", "litter"),
    ("chewy", "retail_us", "https://www.chewy.com/s?query=dog+bed", "bed"),
    ("ulta", "retail_us", "https://www.ulta.com/search?search=mascara", "mascara"),
    ("sephora", "retail_us", "https://www.sephora.com/search?keyword=perfume", "perfume"),
    ("barnesandnoble", "retail_us", "https://www.barnesandnoble.com/s/cookbook", "cookbook"),
    ("guitarcenter", "retail_us", "https://www.guitarcenter.com/search?typeAheadSuggestion=true&Ntt=ukulele", "ukulele"),
    ("newegg", "retail_us", "https://www.newegg.com/p/pl?d=ssd", "ssd"),
    ("bhphotovideo", "retail_us", "https://www.bhphotovideo.com/c/search?q=tripod", "tripod"),
    ("zappos", "retail_us", "https://www.zappos.com/search?term=sandals", "sandal"),
    ("gap", "retail_us", "https://www.gap.com/browse/search.do?searchText=hoodie", "hoodie"),
    ("jcrew", "retail_us", "https://www.jcrew.com/r/search?q=sweater", "sweater"),
    ("ikea-us", "retail_us", "https://www.ikea.com/us/en/search/?q=bookcase", "bookcase"),
    ("officedepot", "retail_us", "https://www.officedepot.com/catalog/search.do?Ntt=stapler", "stapler"),
    ("tractorsupply", "retail_us", "https://www.tractorsupply.com/tsc/search/chicken%20feed", "feed"),
    ("acehardware", "retail_us", "https://www.acehardware.com/search?query=hammer", "hammer"),
    ("menards", "retail_us", "https://www.menards.com/main/search.html?search=shovel", "shovel"),
    ("samsclub", "retail_us", "https://www.samsclub.com/s/coffee", "coffee"),
    ("costco-us", "retail_us", "https://www.costco.com/CatalogSearch?keyword=blender", "blender"),
    ("etsy-us", "retail_us", "https://www.etsy.com/search?q=ceramic+mug", "mug"),
    ("hottopic", "retail_us", "https://www.hottopic.com/search?q=hoodie", "hoodie"),
    # AU / NZ retail
    ("jbhifi", "retail_au", "https://www.jbhifi.com.au/search?query=keyboard", "keyboard"),
    ("harveynorman", "retail_au", "https://www.harveynorman.com.au/search?q=kettle", "kettle"),
    ("thegoodguys", "retail_au", "https://www.thegoodguys.com.au/SearchDisplay?searchTerm=toaster", "toaster"),
    ("officeworks", "retail_au", "https://www.officeworks.com.au/shop/officeworks/search?q=notebook", "notebook"),
    ("bunnings", "retail_au", "https://www.bunnings.com.au/search/products?q=drill", "drill"),
    ("kmart-au", "retail_au", "https://www.kmart.com.au/search/?searchTerm=cushion", "cushion"),
    ("target-au", "retail_au", "https://www.target.com.au/search?text=towel", "towel"),
    ("bigw", "retail_au", "https://www.bigw.com.au/search?text=lego", "lego"),
    ("myer", "retail_au", "https://www.myer.com.au/search?query=handbag", "handbag"),
    ("davidjones", "retail_au", "https://www.davidjones.com/search?q=perfume", "perfume"),
    ("rebelsport", "retail_au", "https://www.rebelsport.com.au/search?q=runners", "runner"),
    ("anaconda", "retail_au", "https://www.anacondastores.com/search?q=tent", "tent"),
    ("bcf", "retail_au", "https://www.bcf.com.au/search?q=fishing+rod", "rod"),
    ("supercheapauto", "retail_au", "https://www.supercheapauto.com.au/search?q=car+battery", "battery"),
    ("chemistwarehouse", "retail_au", "https://www.chemistwarehouse.com.au/search?searchtext=vitamin", "vitamin"),
    ("kogan", "retail_au", "https://www.kogan.com/au/shop/?q=monitor", "monitor"),
    ("catch", "retail_au", "https://www.catch.com.au/search?query=pillow", "pillow"),
    ("noelleeming", "retail_au", "https://www.noelleeming.co.nz/search?q=laptop", "laptop"),
    ("mightyape", "retail_au", "https://www.mightyape.co.nz/search?q=board+game", "game"),
    ("thewarehouse-nz", "retail_au", "https://www.thewarehouse.co.nz/search?q=kettle", "kettle"),
    # EU / UK retail
    ("argos", "retail_eu", "https://www.argos.co.uk/search/kettle/", "kettle"),
    ("johnlewis", "retail_eu", "https://www.johnlewis.com/search?search-term=duvet", "duvet"),
    ("currys", "retail_eu", "https://www.currys.co.uk/search?q=headphones", "headphone"),
    ("very", "retail_eu", "https://www.very.co.uk/search/mirror", "mirror"),
    ("next-uk", "retail_eu", "https://www.next.co.uk/search?w=jeans", "jeans"),
    ("asos", "retail_eu", "https://www.asos.com/search/?q=dress", "dress"),
    ("boots-uk", "retail_eu", "https://www.boots.com/search?text=sunscreen", "sunscreen"),
    ("screwfix", "retail_eu", "https://www.screwfix.com/search?search=drill", "drill"),
    ("otto", "retail_eu", "https://www.otto.de/suche/kaffeemaschine/", "kaffeemaschine"),
    ("mediamarkt-de", "retail_eu", "https://www.mediamarkt.de/de/search.html?query=kopfh%C3%B6rer", "kopfh"),
    ("galaxus", "retail_eu", "https://www.galaxus.ch/en/search?q=monitor", "monitor"),
    ("bol", "retail_eu", "https://www.bol.com/nl/nl/s/?searchtext=koptelefoon", "koptelefoon"),
    ("coolblue", "retail_eu", "https://www.coolblue.nl/zoeken?query=wasmachine", "wasmachine"),
    ("fnac", "retail_eu", "https://www.fnac.com/SearchResult/ResultList.aspx?Search=casque", "casque"),
    ("cdiscount", "retail_eu", "https://www.cdiscount.com/search/10/aspirateur.html", "aspirateur"),
    ("elcorteingles", "retail_eu", "https://www.elcorteingles.es/search-nwx/1/?s=cafetera", "cafetera"),
    ("zalando-uk", "retail_eu", "https://www.zalando.co.uk/catalogue/?q=trainers", "trainer"),
    ("elgiganten", "retail_eu", "https://www.elgiganten.se/search?q=dammsugare", "dammsugare"),
    ("power-no", "retail_eu", "https://www.power.no/search/?q=st%C3%B8vsuger", "støvsuger"),
    ("alza", "retail_eu", "https://www.alza.cz/search.htm?exps=notebook", "notebook"),
    ("allegro", "retail_eu", "https://allegro.pl/listing?string=rower", "rower"),
    ("emag", "retail_eu", "https://www.emag.ro/search/telefon", "telefon"),
    ("hornbach", "retail_eu", "https://www.hornbach.de/s/akkuschrauber", "akkuschrauber"),
    ("decathlon-uk", "retail_eu", "https://www.decathlon.co.uk/search?Ntt=tent", "tent"),
    # Classifieds and marketplaces
    ("craigslist", "classifieds", "https://sfbay.craigslist.org/search/bia?query=road+bike", "bike"),
    ("ebay-uk", "classifieds", "https://www.ebay.co.uk/sch/i.html?_nkw=film+camera", "camera"),
    ("vinted", "classifieds", "https://www.vinted.co.uk/catalog?search_text=jacket", "jacket"),
    ("leboncoin", "classifieds", "https://www.leboncoin.fr/recherche?text=velo", "vélo"),
    ("kleinanzeigen", "classifieds", "https://www.kleinanzeigen.de/s-fahrrad/k0", "fahrrad"),
    ("marktplaats", "classifieds", "https://www.marktplaats.nl/q/fiets/", "fiets"),
    ("tori", "classifieds", "https://www.tori.fi/recommerce/forsale/search?q=polkupy%C3%B6r%C3%A4", "polkupy"),
    ("dba", "classifieds", "https://www.dba.dk/recommerce/forsale/search?q=cykel", "cykel"),
    ("trademe", "classifieds", "https://www.trademe.co.nz/a/marketplace/search?search_string=bike", "bike"),
    ("carousell-sg", "classifieds", "https://www.carousell.sg/search/camera", "camera"),
    ("mercadolibre-ar", "classifieds", "https://listado.mercadolibre.com.ar/bicicleta", "bicicleta"),
    ("avito", "classifieds", "https://www.avito.ru/moskva?q=велосипед", "велосипед"),
    ("olx-pl", "classifieds", "https://www.olx.pl/oferty/q-rower/", "rower"),
    ("kijiji", "classifieds", "https://www.kijiji.ca/b-canada/bike/k0l0", "bike"),
    # Jobs
    ("seek", "jobs", "https://www.seek.com.au/python-jobs", "python"),
    ("indeed-uk", "jobs", "https://uk.indeed.com/jobs?q=python", "python"),
    ("glassdoor", "jobs", "https://www.glassdoor.com/Job/python-jobs-SRCH_KO0,6.htm", "python"),
    ("monster", "jobs", "https://www.monster.com/jobs/search?q=python", "python"),
    ("dice", "jobs", "https://www.dice.com/jobs?q=python", "python"),
    ("weworkremotely", "jobs", "https://weworkremotely.com/remote-jobs/search?term=python", "python"),
    ("arbeitnow", "jobs", "https://www.arbeitnow.com/?search=python", "python"),
    ("welcometothejungle", "jobs", "https://www.welcometothejungle.com/en/jobs?query=python", "python"),
    ("jora", "jobs", "https://au.jora.com/j?q=python", "python"),
    ("cv-library", "jobs", "https://www.cv-library.co.uk/python-jobs", "python"),
    # Property
    ("domain", "property", "https://www.domain.com.au/rent/sydney-nsw-2000/", "rent"),
    ("realestate-au", "property", "https://www.realestate.com.au/rent/in-sydney,+nsw+2000/list-1", "rent"),
    ("rightmove", "property", "https://www.rightmove.co.uk/property-to-rent/London.html", "rent"),
    ("zoopla", "property", "https://www.zoopla.co.uk/to-rent/property/london/", "rent"),
    ("immobilienscout24", "property", "https://www.immobilienscout24.de/Suche/de/berlin/berlin/wohnung-mieten", "wohnung"),
    ("trulia", "property", "https://www.trulia.com/CA/San_Francisco/", "home"),
    ("realtor", "property", "https://www.realtor.com/realestateandhomes-search/Austin_TX", "home"),
    ("seloger", "property", "https://www.seloger.com/immobilier/locations/immo-paris-75/", "appartement"),
    # Travel
    ("booking", "travel", "https://www.booking.com/searchresults.html?ss=Lisbon", "lisbon"),
    ("expedia", "travel", "https://www.expedia.com/Hotel-Search?destination=Lisbon", "lisbon"),
    ("hostelworld", "travel", "https://www.hostelworld.com/st/hostels/europe/portugal/lisbon/", "hostel"),
    ("tripadvisor", "travel", "https://www.tripadvisor.com/Hotels-g189158-Lisbon_Lisbon_District_Central_Portugal-Hotels.html", "hotel"),
    ("skyscanner", "travel", "https://www.skyscanner.net/flights-to/lis/cheap-flights-to-lisbon-airport.html", "lisbon"),
    ("lonelyplanet", "travel", "https://www.lonelyplanet.com/portugal/lisbon", "lisbon"),
    ("viator", "travel", "https://www.viator.com/Lisbon/d538-ttd", "lisbon"),
    ("trainline", "travel", "https://www.thetrainline.com/en/train-times/london-to-manchester", "manchester"),
    # News
    ("abc-au", "news", "https://www.abc.net.au/news/business", "business"),
    ("smh", "news", "https://www.smh.com.au/business", "business"),
    ("bbc", "news", "https://www.bbc.com/news/business", "business"),
    ("cnbc", "news", "https://www.cnbc.com/technology/", "tech"),
    ("apnews", "news", "https://apnews.com/hub/technology", "technology"),
    ("npr", "news", "https://www.npr.org/sections/technology/", "technology"),
    ("dw", "news", "https://www.dw.com/en/business/s-1431", "business"),
    ("aljazeera", "news", "https://www.aljazeera.com/economy/", "economy"),
    ("stuff", "news", "https://www.stuff.co.nz/business", "business"),
    ("scmp", "news", "https://www.scmp.com/business", "business"),
    ("theverge", "news", "https://www.theverge.com/tech", "tech"),
    ("techcrunch", "news", "https://techcrunch.com/category/startups/", "startup"),
    # Government
    ("gov-uk", "gov", "https://www.gov.uk/search/all?keywords=passport", "passport"),
    ("usa-gov", "gov", "https://www.usa.gov/passport", "passport"),
    ("servicesaustralia", "gov", "https://www.servicesaustralia.gov.au/medicare", "medicare"),
    ("ato", "gov", "https://www.ato.gov.au/individuals-and-families", "tax"),
    ("canada-ca", "gov", "https://www.canada.ca/en/services/taxes.html", "tax"),
    ("europa", "gov", "https://european-union.europa.eu/live-work-study_en", "eu"),
    ("nsw-gov", "gov", "https://www.nsw.gov.au/driving-boating-and-transport", "licence"),
    ("irs", "gov", "https://www.irs.gov/filing", "file"),
    # Media and reference
    ("imdb", "media", "https://www.imdb.com/find/?q=alien", "alien"),
    ("goodreads", "media", "https://www.goodreads.com/search?q=dune", "dune"),
    ("bandcamp", "media", "https://bandcamp.com/search?q=jazz", "jazz"),
    ("soundcloud", "media", "https://soundcloud.com/search?q=lofi", "lofi"),
    ("letterboxd", "media", "https://letterboxd.com/search/alien/", "alien"),
    ("archive-org", "media", "https://archive.org/search?query=jazz", "jazz"),
    ("rottentomatoes", "media", "https://www.rottentomatoes.com/search?search=alien", "alien"),
    ("allrecipes", "food", "https://www.allrecipes.com/search?q=lasagna", "lasagna"),
    ("taste-au", "food", "https://www.taste.com.au/search-recipes/?q=lasagne", "lasagne"),
    ("bbcgoodfood", "food", "https://www.bbcgoodfood.com/search?q=lasagne", "lasagne"),
    ("seriouseats", "food", "https://www.seriouseats.com/search?q=lasagna", "lasagna"),
    ("ubereats", "food", "https://www.ubereats.com/au/category/sydney-nsw/pizza", "pizza"),
    # Cars
    ("autotrader-uk", "cars", "https://www.autotrader.co.uk/car-search?make=Toyota&model=Corolla&postcode=SW1A1AA", "corolla"),
    ("cars-com", "cars", "https://www.cars.com/shopping/results/?makes[]=toyota&models[]=toyota-corolla&stock_type=used", "corolla"),
    ("drive-au", "cars", "https://www.drive.com.au/cars-for-sale/search/toyota/corolla/", "corolla"),
    ("mobile-de", "cars", "https://suchen.mobile.de/fahrzeuge/search.html?ms=24100%3B13&vc=Car", "golf"),
    ("cargurus", "cars", "https://www.cargurus.com/Cars/l-Used-Toyota-Corolla-d295", "corolla"),
    ("edmunds", "cars", "https://www.edmunds.com/toyota/corolla/", "corolla"),
    # Dev
    ("npmjs", "dev", "https://www.npmjs.com/search?q=markdown", "markdown"),
    ("pypi", "dev", "https://pypi.org/search/?q=markdown", "markdown"),
    ("crates", "dev", "https://crates.io/search?q=markdown", "markdown"),
    ("mdn", "dev", "https://developer.mozilla.org/en-US/search?q=fetch", "fetch"),
    ("gitlab", "dev", "https://gitlab.com/explore/projects?name=markdown", "markdown"),
    ("huggingface", "dev", "https://huggingface.co/models?search=whisper", "whisper"),
    ("producthunt", "dev", "https://www.producthunt.com/search?q=markdown", "markdown"),
    ("devto", "dev", "https://dev.to/search?q=python", "python"),
    # Social
    ("mastodon", "social", "https://mastodon.social/@Mastodon", "mastodon"),
    ("tumblr", "social", "https://www.tumblr.com/search/film%20photography", "film"),
    ("quora", "social", "https://www.quora.com/search?q=film%20camera", "camera"),
    ("medium", "social", "https://medium.com/search?q=film%20photography", "film"),
    ("substack", "social", "https://substack.com/search/film%20photography", "film"),
    ("twitch", "social", "https://www.twitch.tv/directory/category/chess", "chess"),
    ("landsend", "retail_us", "https://www.landsend.com/shop/search?Ntt=fleece", "fleece"),
    ("rockler", "retail_us", "https://www.rockler.com/catalogsearch/result/?q=clamp", "clamp"),
    ("hobbylobby", "retail_us", "https://www.hobbylobby.com/search/?text=yarn", "yarn"),
    ("basspro", "retail_us", "https://www.basspro.com/shop/en/search?searchTerm=tackle%20box", "tackle"),
    ("sierra", "retail_us", "https://www.sierra.com/s~jacket/", "jacket"),
    ("evo", "retail_us", "https://www.evo.com/shop?text=snowboard", "snowboard"),
    ("zumiez", "retail_us", "https://www.zumiez.com/catalogsearch/result/?q=skateboard", "skateboard"),
    ("crutchfield", "retail_us", "https://www.crutchfield.com/p_search.aspx?search=receiver", "receiver"),
    ("musiciansfriend", "retail_us", "https://www.musiciansfriend.com/search?Ntt=ukulele", "ukulele"),
    ("reverb", "retail_us", "https://reverb.com/marketplace?query=telecaster", "telecaster"),
    ("revolve", "retail_us", "https://www.revolve.com/r/search?search=dress", "dress"),
    ("shopbop", "retail_us", "https://www.shopbop.com/s/query/boots", "boot"),
    ("mrporter", "retail_us", "https://www.mrporter.com/en-us/mens/search?keywords=shirt", "shirt"),
    ("flooranddecor", "retail_us", "https://www.flooranddecor.com/search?q=tile", "tile"),
    ("zoro", "retail_us", "https://www.zoro.com/search?q=wrench", "wrench"),
    ("grainger", "retail_us", "https://www.grainger.com/search?searchQuery=gloves", "glove"),
    ("webstaurantstore", "retail_us", "https://www.webstaurantstore.com/search/sheet-pan.html", "pan"),
    ("vitacost", "retail_us", "https://www.vitacost.com/productsearch.aspx?t=protein", "protein"),
    ("iherb", "retail_us", "https://www.iherb.com/search?kw=magnesium", "magnesium"),
    ("carters", "retail_us", "https://www.carters.com/search?q=pajamas", "pajama"),
    ("petcircle", "retail_au", "https://www.petcircle.com.au/search?q=dog%20food", "dog"),
    ("adorebeauty", "retail_au", "https://www.adorebeauty.com.au/search?q=serum", "serum"),
    ("mecca", "retail_au", "https://www.mecca.com/en-au/search/?q=lipstick", "lipstick"),
    ("raysoutdoors", "retail_au", "https://www.raysoutdoors.com.au/search?q=swag", "swag"),
    ("snowys", "retail_au", "https://www.snowys.com.au/search?q=sleeping+bag", "sleeping"),
    ("paddypallin", "retail_au", "https://www.paddypallin.com.au/search?q=jacket", "jacket"),
    ("qbd", "retail_au", "https://www.qbd.com.au/search/?q=atlas", "atlas"),
    ("ebgames", "retail_au", "https://www.ebgames.com.au/search?q=controller", "controller"),
    ("freedom", "retail_au", "https://www.freedom.com.au/search?q=sofa", "sofa"),
    ("adairs", "retail_au", "https://www.adairs.com.au/search/?q=quilt", "quilt"),
    ("bedbathntable", "retail_au", "https://www.bedbathntable.com.au/search?q=towel", "towel"),
    ("pbtech", "retail_au", "https://www.pbtech.co.nz/search?sf=monitor", "monitor"),
    ("sportsdirect", "retail_eu", "https://www.sportsdirect.com/searchresults?descriptionfilter=football", "football"),
    ("scan", "retail_eu", "https://www.scan.co.uk/search?q=ssd", "ssd"),
    ("overclockers", "retail_eu", "https://www.overclockers.co.uk/search?sSearch=keyboard", "keyboard"),
    ("chainreaction", "retail_eu", "https://www.chainreactioncycles.com/s?q=helmet", "helmet"),
    ("diy-bq", "retail_eu", "https://www.diy.com/search?term=paint", "paint"),
    ("dunelm", "retail_eu", "https://www.dunelm.com/search?searchTerm=cushion", "cushion"),
    ("superdrug", "retail_eu", "https://www.superdrug.com/search?text=shampoo", "shampoo"),
    ("waterstones", "retail_eu", "https://www.waterstones.com/books/search/term/gardening", "garden"),
    ("cotswold", "retail_eu", "https://www.cotswoldoutdoor.com/search?q=boots", "boot"),
    ("ocado", "retail_eu", "https://www.ocado.com/search?entry=coffee", "coffee"),
    ("thalia", "retail_eu", "https://www.thalia.de/suche?sq=krimi", "krimi"),
    ("notebooksbilliger", "retail_eu", "https://www.notebooksbilliger.de/produkte/maus", "maus"),
    ("bergfreunde", "retail_eu", "https://www.bergfreunde.de/search/?q=rucksack", "rucksack"),
    ("aboutyou", "retail_eu", "https://www.aboutyou.de/suche?term=jacke", "jacke"),
    ("castorama", "retail_eu", "https://www.castorama.fr/search?term=perceuse", "perceuse"),
    ("manomano", "retail_eu", "https://www.manomano.fr/recherche/perceuse", "perceuse"),
    ("laredoute", "retail_eu", "https://www.laredoute.fr/psrch/psrch.aspx?kwrd=pull", "pull"),
    ("gamma", "retail_eu", "https://www.gamma.nl/assortiment/zoeken?text=boormachine", "boormachine"),
    ("hema", "retail_eu", "https://www.hema.nl/zoeken?q=mok", "mok"),
    ("xxl", "retail_eu", "https://www.xxl.no/search?query=ski", "ski"),
    ("clasohlson", "retail_eu", "https://www.clasohlson.com/se/search?text=lampa", "lampa"),
    ("xkom", "retail_eu", "https://www.x-kom.pl/szukaj?q=monitor", "monitor"),
    ("czc", "retail_eu", "https://www.czc.cz/monitor/hledat", "monitor"),
    ("digitec", "retail_eu", "https://www.digitec.ch/en/search?q=headphones", "headphone"),
    ("myntra", "retail_asia", "https://www.myntra.com/shirts", "shirt"),
    ("croma", "retail_asia", "https://www.croma.com/searchB?q=headphones", "headphone"),
    ("qoo10", "retail_asia", "https://www.qoo10.sg/s/?keyword=sunscreen", "sunscreen"),
    ("bukalapak", "retail_asia", "https://www.bukalapak.com/products?search%5Bkeywords%5D=sepatu", "sepatu"),
    ("jumia", "retail_asia", "https://www.jumia.com.ng/catalog/?q=phone", "phone"),
    ("paris-cl", "retail_asia", "https://www.paris.cl/search?q=zapatillas", "zapatilla"),
    ("coppel", "retail_asia", "https://www.coppel.com/SearchDisplay?searchTerm=colchon", "colch"),
    ("willhaben", "classifieds", "https://www.willhaben.at/iad/kaufen-und-verkaufen/marktplatz?keyword=fahrrad", "fahrrad"),
    ("ricardo", "classifieds", "https://www.ricardo.ch/de/s/velo", "velo"),
    ("jiji", "classifieds", "https://jiji.ng/search?query=iphone", "iphone"),
    ("dubizzle", "classifieds", "https://dubai.dubizzle.com/search/?keyword=bicycle", "bicycle"),
    ("bazos", "classifieds", "https://www.bazos.cz/search.php?hledat=kolo", "kolo"),
    ("jofogas", "classifieds", "https://www.jofogas.hu/magyarorszag?q=kerekp%C3%A1r", "kerékpár"),
    ("njuskalo", "classifieds", "https://www.njuskalo.hr/search/?keywords=bicikl", "bicikl"),
    ("donedeal", "classifieds", "https://www.donedeal.ie/all?words=bike", "bike"),
    ("adverts-ie", "classifieds", "https://www.adverts.ie/for-sale/q_bike/", "bike"),
    ("ebay-de", "classifieds", "https://www.ebay.de/sch/i.html?_nkw=fahrrad", "fahrrad"),
    ("yahoo-auctions", "classifieds", "https://auctions.yahoo.co.jp/search/search?p=%E3%82%AB%E3%83%A1%E3%83%A9", "カメラ"),
    ("tradera", "classifieds", "https://www.tradera.com/search?q=cykel", "cykel"),
    ("mercadolibre-cl", "classifieds", "https://listado.mercadolibre.cl/bicicleta", "bicicleta"),
    ("jobs-ch", "jobs", "https://www.jobs.ch/en/vacancies/?term=python", "python"),
    ("karriere-at", "jobs", "https://www.karriere.at/jobs/python", "python"),
    ("infojobs", "jobs", "https://www.infojobs.net/jobsearch/search-results/list.xhtml?keyword=python", "python"),
    ("jobindex", "jobs", "https://www.jobindex.dk/jobsoegning?q=python", "python"),
    ("jobserve", "jobs", "https://www.jobserve.com/gb/en/Job-Search/?q=python", "python"),
    ("cwjobs", "jobs", "https://www.cwjobs.co.uk/jobs/python", "python"),
    ("adzuna", "jobs", "https://www.adzuna.com.au/search?q=python", "python"),
    ("careerone", "jobs", "https://www.careerone.com.au/jobs/python", "python"),
    ("mycareersfuture", "jobs", "https://www.mycareersfuture.gov.sg/search?search=python", "python"),
    ("bayt", "jobs", "https://www.bayt.com/en/uae/jobs/python-jobs/", "python"),
    ("computrabajo", "jobs", "https://mx.computrabajo.com/trabajo-de-python", "python"),
    ("remotive", "jobs", "https://remotive.com/remote-jobs?query=python", "python"),
    ("workatastartup", "jobs", "https://www.workatastartup.com/jobs?query=python", "python"),
    ("realestate-nz", "property", "https://www.realestate.co.nz/residential/sale/auckland", "auckland"),
    ("allhomes", "property", "https://www.allhomes.com.au/sale/search?region=canberra-act", "canberra"),
    ("homely", "property", "https://www.homely.com.au/for-sale/brisbane-qld-4000/real-estate", "brisbane"),
    ("primelocation", "property", "https://www.primelocation.com/for-sale/property/edinburgh/", "edinburgh"),
    ("myhome-ie", "property", "https://www.myhome.ie/residential/dublin/property-for-sale", "dublin"),
    ("pararius", "property", "https://www.pararius.com/apartments/amsterdam", "amsterdam"),
    ("fotocasa", "property", "https://www.fotocasa.es/es/comprar/viviendas/madrid-capital/todas-las-zonas/l", "madrid"),
    ("immobiliare", "property", "https://www.immobiliare.it/vendita-case/milano/", "milano"),
    ("homegate", "property", "https://www.homegate.ch/rent/real-estate/city-zurich/matching-list", "zürich"),
    ("propertyguru", "property", "https://www.propertyguru.com.sg/property-for-rent", "rent"),
    ("magicbricks", "property", "https://www.magicbricks.com/property-for-sale-in-pune-pppfs", "pune"),
    ("zumper", "property", "https://www.zumper.com/apartments-for-rent/austin-tx", "austin"),
    ("hotpads", "property", "https://hotpads.com/austin-tx/apartments-for-rent", "austin"),
    ("agoda", "travel", "https://www.agoda.com/city/bangkok-th.html", "bangkok"),
    ("trip-com", "travel", "https://www.trip.com/hotels/bangkok-hotels-list-359/", "bangkok"),
    ("kiwi", "travel", "https://www.kiwi.com/en/search/results/sydney-new-south-wales-australia/tokyo-japan", "tokyo"),
    ("wotif", "travel", "https://www.wotif.com/Melbourne-Hotels.d178283.Travel-Guide-Hotels", "melbourne"),
    ("webjet", "travel", "https://www.webjet.com.au/flights/melbourne/", "melbourne"),
    ("lastminute", "travel", "https://www.lastminute.com/hotels/italy/rome", "rome"),
    ("omio", "travel", "https://www.omio.com/trains/berlin/munich", "munich"),
    ("flixbus", "travel", "https://www.flixbus.com/bus/berlin", "berlin"),
    ("seat61", "travel", "https://www.seat61.com/trains-and-routes/london-to-paris-by-train.htm", "paris"),
    ("atlasobscura", "travel", "https://www.atlasobscura.com/things-to-do/lisbon-portugal", "lisbon"),
    ("independent", "news", "https://www.independent.co.uk/news/business", "business"),
    ("irishtimes", "news", "https://www.irishtimes.com/business/", "business"),
    ("nzherald", "news", "https://www.nzherald.co.nz/business/", "business"),
    ("rnz", "news", "https://www.rnz.co.nz/news/business", "business"),
    ("cbc", "news", "https://www.cbc.ca/news/business", "business"),
    ("latimes", "news", "https://www.latimes.com/business", "business"),
    ("usatoday", "news", "https://www.usatoday.com/money/", "money"),
    ("marketwatch", "news", "https://www.marketwatch.com/latest-news", "stock"),
    ("japantimes", "news", "https://www.japantimes.co.jp/business/", "business"),
    ("straitstimes", "news", "https://www.straitstimes.com/business", "business"),
    ("thehindu", "news", "https://www.thehindu.com/business/", "business"),
    ("france24", "news", "https://www.france24.com/en/business-tech/", "business"),
    ("euronews", "news", "https://www.euronews.com/business", "business"),
    ("tagesschau", "news", "https://www.tagesschau.de/wirtschaft", "wirtschaft"),
    ("nos", "news", "https://nos.nl/nieuws/economie", "economie"),
    ("gov-ie", "gov", "https://www.gov.ie/en/search/?q=passport", "passport"),
    ("ird", "gov", "https://www.ird.govt.nz/income-tax", "tax"),
    ("abs", "gov", "https://www.abs.gov.au/statistics/economy", "economy"),
    ("ontario", "gov", "https://www.ontario.ca/page/health-care-ontario", "health"),
    ("gov-sg", "gov", "https://www.gov.sg/explainers", "singapore"),
    ("service-public", "gov", "https://www.service-public.fr/particuliers/vosdroits/N360", "passeport"),
    ("weather-gov", "gov", "https://www.weather.gov/safety/", "safety"),
    ("studentaid", "gov", "https://studentaid.gov/understand-aid/types", "aid"),
    ("dmv-ca", "gov", "https://www.dmv.ca.gov/portal/driver-licenses-identification-cards/", "license"),
    ("justwatch", "media", "https://www.justwatch.com/au/search?q=alien", "alien"),
    ("tvmaze", "media", "https://www.tvmaze.com/search?q=office", "office"),
    ("setlistfm", "media", "https://www.setlist.fm/search?query=radiohead", "radiohead"),
    ("songkick", "media", "https://www.songkick.com/search?query=radiohead", "radiohead"),
    ("boardgamegeek", "media", "https://boardgamegeek.com/geeksearch.php?action=search&objecttype=boardgame&q=catan", "catan"),
    ("britannica", "media", "https://www.britannica.com/search?query=volcano", "volcano"),
    ("ifixit", "media", "https://www.ifixit.com/Search?query=iphone%20battery", "battery"),
    ("instructables", "media", "https://www.instructables.com/search/?q=bookshelf", "bookshelf"),
    ("recipetineats", "food", "https://www.recipetineats.com/?s=lasagne", "lasagne"),
    ("bonappetit", "food", "https://www.bonappetit.com/search?q=lasagna", "lasagna"),
    ("food52", "food", "https://food52.com/recipes/search?q=lasagna", "lasagna"),
    ("simplyrecipes", "food", "https://www.simplyrecipes.com/search?q=lasagna", "lasagna"),
    ("chefkoch", "food", "https://www.chefkoch.de/rs/s0/lasagne/Rezepte.html", "lasagne"),
    ("marmiton", "food", "https://www.marmiton.org/recettes/recherche.aspx?aqt=lasagnes", "lasagne"),
    ("giallozafferano", "food", "https://www.giallozafferano.it/ricerca-ricette/lasagne/", "lasagn"),
    ("opentable", "food", "https://www.opentable.com/s?term=italian&metroId=8", "italian"),
    ("autotrader-au", "cars", "https://www.autotrader.com.au/for-sale/toyota/corolla", "corolla"),
    ("coches-net", "cars", "https://www.coches.net/toyota/corolla/segunda-mano/", "corolla"),
    ("autotrader-ca", "cars", "https://www.autotrader.ca/cars/toyota/corolla/", "corolla"),
    ("motortrend", "cars", "https://www.motortrend.com/cars/toyota/corolla/", "corolla"),
    ("carwow", "cars", "https://www.carwow.co.uk/toyota/corolla", "corolla"),
    ("redbook", "cars", "https://www.redbook.com.au/cars/research/toyota/corolla", "corolla"),
    ("nuget", "dev", "https://www.nuget.org/packages?q=json", "json"),
    ("pubdev", "dev", "https://pub.dev/packages?q=http", "http"),
    ("artifacthub", "dev", "https://artifacthub.io/packages/search?ts_query_web=nginx", "nginx"),
    ("addons-mozilla", "dev", "https://addons.mozilla.org/en-US/firefox/search/?q=dark%20mode", "dark"),
    ("sourceforge", "dev", "https://sourceforge.net/directory/?q=backup", "backup"),
    ("codeberg", "dev", "https://codeberg.org/explore/repos?q=markdown", "markdown"),
    ("alternativeto", "dev", "https://alternativeto.net/browse/search/?q=notion", "notion"),
    ("caniuse", "dev", "https://caniuse.com/?search=grid", "grid"),
    ("lemmy", "social", "https://lemmy.world/search?q=photography&type=All", "photography"),
    ("slashdot", "social", "https://slashdot.org/index2.pl?fhfilter=linux", "linux"),
    ("behance", "social", "https://www.behance.net/search/projects?search=poster", "poster"),
    ("dribbble", "social", "https://dribbble.com/search/dashboard", "dashboard"),
    ("strava", "social", "https://www.strava.com/clubs/search?text=running", "running"),
    ("wattpad", "social", "https://www.wattpad.com/search/mystery", "mystery"),
    ("telegram", "social", "https://t.me/s/durov", "telegram"),
    ("kickstarter", "social", "https://www.kickstarter.com/discover/advanced?term=board+game", "game"),
]


def main():
    used = set(json.load(open(sys.argv[1])))

    def brand(host):
        """The site's own name: ebay for ebay.co.uk, ebay.de and ebay.com.au alike."""
        parts = host.split(".")
        return parts[-3] if len(parts) >= 3 and parts[-2] in ("co", "com", "org", "net", "gov", "govt", "ac") else parts[-2]
    used_brands = {brand(h) for h in used if "." in h}
    cases, seen = [], set()
    for site, wall, url, expect in CANDIDATES:
        host = url.split("/")[2].removeprefix("www.")
        # The same brand on another country's domain is not a fresh site.
        if host in used or brand(host) in used_brands or site in seen:
            continue
        seen.add(site)
        cases.append({"site": site, "wall": wall, "url": url, "expect": expect})
    note = ("Fifth held-out set, 10 October 2026: sites chosen from general knowledge before any of their pages "
            "was read, none on an earlier set or spot check (" + str(len(used)) + " hosts excluded "
            "automatically). Same rules as before: 800+ characters and the expect pattern at least 3 times. "
            "Some URLs may be dead or wrong; that counts against every arm alike. Use once.")
    # Round-robin across categories so no kind of site dominates the 150.
    by_kind = {}
    for case in cases:
        by_kind.setdefault(case["wall"], []).append(case)
    picked = []
    while len(picked) < 150 and any(by_kind.values()):
        for kind in sorted(by_kind):
            if by_kind[kind] and len(picked) < 150:
                picked.append(by_kind[kind].pop(0))
    json.dump({"schema": "frankensurf.toolbench-heldout/v1", "note": note, "cases": picked},
              sys.stdout, indent=1, ensure_ascii=False)
    print(file=sys.stderr)
    print(len(cases), "candidates kept after excluding used hosts", file=sys.stderr)


if __name__ == "__main__":
    main()
